name: CI

on:
  push:
  pull_request:
env:
    CARGO_TERM_COLOR: always
    RUST_BACKTRACE: 1
permissions: {}

jobs:
    check:
        name: Check - ${{ matrix.task }}
        runs-on: ubuntu-latest
        permissions:
            contents: read
        strategy:
            fail-fast: false
            matrix:
                task: [fmt --check, lint, docs]

        steps:
            - name: Checkout repository
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  persist-credentials: false

            - name: Setup build cache
              uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

            - name: Setup cargo-rbmt
              uses: ./.github/actions/setup-rbmt

            - name: "Run ${{ matrix.task }}"
              run: cargo rbmt ${{ matrix.task }}

    test:
        name: Test - ${{ matrix.toolchain }} toolchain, ${{ matrix.lockfile }} deps
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                toolchain: [stable, msrv]
                lockfile: [minimal, recent]
                exclude:
                    # Exclude MSRV toolchain + `Cargo-recent.lock`
                    - toolchain: msrv
                      lockfile: recent
                    # Exclude stable toolchain + `Cargo-minimal.lock`
                    - toolchain: stable
                      lockfile: minimal

        steps:
            - name: Checkout repository
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  persist-credentials: false

            - name: Setup build cache
              uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

            - name: Setup cargo-rbmt
              uses: ./.github/actions/setup-rbmt

            - name: Run tests
              run: cargo rbmt test --toolchain ${{ matrix.toolchain }} --lock-file ${{ matrix.lockfile }}
